### ISSUE TITLE
DHT22 AM2302 Sensor not working on Wio Terminal in release mode (debugging mode is working)

### ISSUE THREAD

**Issue by RoSchmi** [Seeed-Studio/Grove_Temperature_And_Humidity_Sensor#15]
Hello, I'm using an DHT22 AM2302 Temperature/Humidity Sensor on the Wio Terminal. I work with PlatformIO and have a J-Link debugger attached. 
When I deploy the code via the J-Link debugger everything works fine, even if I detach the debugger. However if I deploy the code the normal way via the USB Port I can get no valid readings from the sensor. 
I suspect that there is a timing problem when the code is compiled in release mode.
Can you please try on your side, if you can confirm my observations?

**Comment by RoSchmi** [comment]
May be that the cause for the unexpected behavior lies in my application. With your test sketch it is working. I'll investigate further.

**Comment by RoSchmi** [comment]
I finally solved the issue for me by changing the value of the  'Count' parameter in the constructor of the DHT class from 25 (default value) to 13. With this value it worked for me on the Wio Terminal in release mode and debug mode. The 'Count' value determins the timespan after which the MCU is looking (after a level shifting) wether the signal coming from the dht module is '0' or '1'
DHT dht(DHTPIN, DHTTYPE, 20);

**Comment by BartTK** [comment]
I had a similar issue with the DHT22 on the NANO 33 IOT. It used to work in the past, but suddenly it doesn't work anymore. This is a 48 MHz chip which would normally result in a COUNT of 18. Measuring the actual values shows that a 0-bit takes an average of 6 counts and a 1-bit ends up at 16 counts. So halving the COUNT value to 9 sounds about right. That indeed did the trick; it works like a charm with the COUNT at 9.

Makes me wonder whether something has changed recently in the Arduino libs or in the compiler that makes is slightly slower...

**Comment by Pillar1989** [comment]
@IsQianGe

**Comment by tyihuang** [comment]
> 我在 NANO 33 IOT 上的 DHT22 遇到了类似的问题。以前可以用，但突然就不行了。这是一个 48 MHz 芯片，通常会导致 COUNT 为 18。测量实际值显示 0 位平均为 6 个计数，而 1 位最终为 16 个计数。所以将 COUNT 值减半到 9 听起来是正确的。这确实做到了。COUNT 为 9 时，它就像一个魅力。
> 
> 让我想知道最近在 Arduino 库或编译器中是否发生了一些变化，使其稍微变慢了......

Hello, I use sedeuino XIAO to test (the board CPU is SAMD21, frequency is 48MHZ) and found that the default setting of COUNT is 18, it can be recognized and printed normally, please rule out whether your main control board problems? Please refer to the following screenshot for details

![image](https://user-images.githubusercontent.com/56999025/124246330-69479700-db53-11eb-9869-778ca67ea924.png)
![image](https://user-images.githubusercontent.com/56999025/124246397-7795b300-db53-11eb-947f-ed3a9729e50a.png)

**Comment by BartTK** [comment]
For me, the default `COUNT` (or `_count` in this screenshot) indeed used to be 18. But that didn't work for me. Therefore I changed it to 9 locally on my PC. I haven't pushed that change here to Github because I was a bit afraid that it might break something for other 48Mhz chips, different versions of the compiler, different version of the lib... Both your observation and the fact that a value of 18 used to work me in the past seem to confirm this fear.

Using this counter here doesn't feel very reliable as it depends on a number of things like chip, frequency, compiler version, library versions... I think this might work better we would just use `micros()` to measure the duration of the high signal. Kinda like [this other DHT lib](https://github.com/RobTillaart/DHTNew/blob/master/dhtnew.cpp#L350) is doing. No need to bother with all different frequencies and those kind of things. Just measure the amount of microseconds and compare that to the specs of the sensor.
